"""date_mod

Revision ID: 140b6c479af0
Revises: ff423c4295f0
Create Date: 2023-10-08 18:38:42.499903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140b6c479af0'
down_revision: Union[str, None] = 'ff423c4295f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index('ix_contacts_date_of_birth', table_name='contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_contacts_date_of_birth', 'contacts', ['date_of_birth'], unique=False)
    op.alter_column('contacts', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
